### ISSUE TITLE
When I open this library I get ESP8266.h:32:28: fatal error: SoftwareSerial.h: No such file or directory

### ISSUE THREAD

**Issue by benjgorman** [Circuito-io/ESP8266_SoftwareSerial#1]
I'm trying to use the library, but can't import the library as a .zip or compile it?

<img width="500" alt="screen shot 2018-02-03 at 02 22 59" src="https://user-images.githubusercontent.com/622001/35762100-43448112-0889-11e8-8bf0-27ae9cd511d7.png">

**Comment by Robohad** [comment]
Hi benjgorman,

SoftwareSerial.h is a built in library of the Arduino IDE.

I downloaded the code also, it compiled without any problems at all.
I am using the Arduino IDE 1.8.3 while you are using 1.6.5 - could be the issue.

Try to update it to the latest version from the Arduino website and see if it fixes the problem.
If it doesn't we will be happy to help

**Comment by benjgorman** [comment]
Ah, I have two version of Arduino installed at the moment. Rookie mistake. Thanks!
